language: generic

services:
  - docker

env:
  - TAGS=latest,0.10.6 ARCHS=386,amd64,arm5,arm6,arm7,arm64 PLUGINS= SET=raw
  - TAGS=latest,0.10.6 ARCHS=386,amd64,arm5,arm6,arm7,arm64 PLUGINS=http.cors,http.expires,http.filter,http.prometheus,http.realip SET=semi

script:
  - TAGS=$TAGS ARCHS=$ARCHS PLUGINS=$PLUGINS ./build.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push marcbachmann/caddy;
    fi
